Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.

In [5]:
import torch
import numpy as np

Initializing a Tensor directly from data

In [6]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

Initializing a Tensor from a NumPy array

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

Initializing a Tensor from another tensor<br/>
The new tensor retains the properties(shape, datatype)

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3913, 0.9946],
        [0.1400, 0.3516]]) 



Initializing a Tensor with random or constant values

In [10]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8998, 0.4076, 0.4232],
        [0.9840, 0.4649, 0.5236]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



Attributes of a Tensor

In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: \n {tensor.shape} \n")
print(f"Datatype of tensor: \n {tensor.dtype} \n")
print(f"Device tensor is stored on: \n {tensor.device} \n")

Shape of tensor: 
 torch.Size([3, 4]) 

Datatype of tensor: 
 torch.float32 

Device tensor is stored on: 
 cpu 



By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).<br/>
 Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Standard numpy-like indexing and slicing

In [14]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ',tensor[:, 0])
print('Last column: ',tensor[:, -1])
tensor[:, 1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Arithmetic operations

In [16]:
# This computes the matrix multiplication between two tensors.
# y1, y2, y3 will have the same value.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product.
# z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors 

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>
